<a href="https://colab.research.google.com/github/Mu-Hasnain/DataScienceWithPython/blob/main/NumpyForDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to Numpy**

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.
*************************************

**Why Use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


In [1]:
#importing module
import numpy as np
#NumPy is usually imported under the np alias.


In [2]:
#scalar
a = 5

In [3]:
#Vector | one dimensional
b = [1, 2, 3]

In [4]:
#matrix | two dimensional
c = [[1, 2, 3], [4, 5, 6], [7,8,9]]

In [5]:
vector = np.array(b)

In [6]:
vector 

array([1, 2, 3])

In [9]:
vector1 = np.array(c)

In [10]:
vector1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x = np.arange(0, 10)

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Common NumPy Methods**

In [22]:
np.random.rand(5)

array([0.33570347, 0.77451219, 0.4557325 , 0.63790781, 0.95444782])

In [23]:
np.random.rand(5,5)

array([[0.23862409, 0.47742799, 0.21187018, 0.23550913, 0.20287625],
       [0.96627518, 0.5305395 , 0.48943689, 0.83435445, 0.43670454],
       [0.84237571, 0.54582866, 0.64943637, 0.63942584, 0.89951476],
       [0.00289656, 0.72651426, 0.73782671, 0.42394362, 0.00951795],
       [0.53471107, 0.25293366, 0.56308544, 0.33809072, 0.65742319]])

In [24]:
np.random.randn(2)

array([0.30620825, 0.75914392])

In [26]:
np.random.randint(10, 100)

89

In [27]:
np.random.randint(10, 100, 20)

array([48, 56, 30, 82, 87, 92, 18, 57, 79, 39, 19, 40, 18, 50, 48, 95, 31,
       53, 74, 32])

In [28]:
#creating Numpy array uisng Random Number method
random_arr = np.random.randint(0, 50, 10)

In [29]:
random_arr

array([31, 36, 33,  5,  8,  3,  9,  1, 15, 29])

In [30]:
#reshaping Numpy array
random_arr.reshape(2, 5)

array([[31, 36, 33,  5,  8],
       [ 3,  9,  1, 15, 29]])

In [31]:
random_arr.max()

36

In [32]:
random_arr.min()

1

In [33]:
#returing index of maximum number :
random_arr.argmax()

1

In [34]:
#returing index of minimum number :
random_arr.argmin()

7

In [35]:
#checking Numpy array shape 1D | 2D
random_arr.shape

(10,)

 1D - NumPy Array 

 =>>NumPy Array Slicing

 Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [37]:
#creating 1D numpy array:
arr = np.arange(20, 31)

In [38]:
arr 

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr[3]

23

In [40]:
arr[1:5]

array([21, 22, 23, 24])

In [41]:
arr[:6]

array([20, 21, 22, 23, 24, 25])

In [42]:
arr[5:]

array([25, 26, 27, 28, 29, 30])

In [44]:
#broadcasting of Numpy array
arr[0:5] = 100

In [45]:
arr

array([100, 100, 100, 100, 100,  25,  26,  27,  28,  29,  30])

In [47]:
second_arr = np.arange(21, 31)

In [48]:
second_arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
#copy
second_arr_copy = np.copy(arr)

**2D - NumPy Array**

In [53]:
#creating 2d numpy array
array2d = np.array([[3, 4, 5],[6, 7, 8],[9, 10, 11]])

In [54]:
array2d

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
#Slicing
array2d[0][1]

4

In [56]:
array2d[1]

array([6, 7, 8])

In [57]:
array2d[1,1]

7

In [58]:
array2d[:2,1:]

array([[4, 5],
       [7, 8]])

In [59]:
array2d[:2]

array([[3, 4, 5],
       [6, 7, 8]])

In [60]:
arr = np.arange(1, 11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#creating array with condition
cond_arr = arr > 5

In [63]:
cond_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[cond_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[arr<3]

array([1, 2])

In [67]:
arr_2d = np.arange(50).reshape(5, 10)

In [68]:
arr_2d 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr_2d[2:4,4:]

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39]])

**NumPy Operations**

> Array with Scalar

> Array with Array

> Universal array function

In [71]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# Addition 
add = arr + arr
add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
#subtraction
sub = arr - arr
sub


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
#multplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
#division

arr / 100


array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [78]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [77]:
#array Square
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [81]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])